### ISSUE TITLE
Create a function that takes filenames as input and run the pipeline

### ISSUE THREAD

**Issue by stemangiola** [Melbourne-COVID-Predict/jascap#17]

**Comment by susansjy22** [comment]
Pipeline can now be run by calling function run_targets_pipeline(). 

Arguments required are: Input_data (file_path), store (store_directory), input_reference (input_reference_path), tissue ("pbmc", "solid", "atypical"), filter_input (TRUE/FALSE). 

Other argument specifications: computing_resources, debug_step, filter_input, RNA_assay_name, sample_column

View output with:
tar_read(preprocessing_output_S, store = store)
