### ISSUE TITLE
Your function has non existing default argument

### ISSUE THREAD

**Issue by stemangiola** [Melbourne-COVID-Predict/jascap#34]
this line

https://github.com/stemangiola/HPCell/blob/27adf7ca9fa407cef7e8ba8875f09ca01e400eff/R/execute_pipeline.R#L9

has a default value of `input_reference_path`, while it should have value `NULL`. 

This is because `input_reference_path` does not exist anywhere.

**Comment by susansjy22** [comment]
Fixed!
