### ISSUE TITLE
Imrove unit tests

### ISSUE THREAD

**Issue by stemangiola** [Melbourne-COVID-Predict/jascap#35]
Rather than only testing if a function has worked and is a S3 object, each test should test specific properties of the output of a function. For example

- The annotation step, produces a tibble output with `3` column, if seurat_reference is set
- The annotation step, produces a tibble output with `2` column, if seurat_reference is NOT set
- The empty droplet filtering step, produce an output with less cells (rows) than the seurat input (cols)
- and so on..

**Comment by susansjy22** [comment]
Each test now checks the specific characteristics of each output
