### ISSUE TITLE
Improve README

### ISSUE THREAD

**Issue by stemangiola** [Melbourne-COVID-Predict/jascap#37]
- [x]  you can drop this

Clone the repository

git clone git@github.com:susansjy22/HPCell.git

- [x] you should point to the main repo in my github

replace this 
```
remote::install_github("git@github.com:susansjy22/HPCell.git")

```

with 

```
remote::install_github("stemangiola/HPCell")
```

- [x] Move this, below, where you give another example of execution with reference. The base example should not include this

```r
# Load reference data 
input_reference_path <- "reference_azimuth.rds"
reference_url<- "https://atlas.fredhutch.org/data/nygc/multimodal/pbmc_multimodal.h5seurat"
download.file(reference_url, input_reference_path)
LoadH5Seurat(input_reference_path) |> saveRDS(input_reference_path)
```

- [x] store should be `"./"` , because this is already the default, you can drop the store variable

```
store <- "~/HPCell/pipeline_store"
```

- [x] Drop the default arguments, let's keep it simple

```r
preprocessed_seurat = run_targets_pipeline(
    input_data = file_path, 
    tissue = tissue,
    filter_input = TRUE, 
    RNA_assay_name 
)
```

**Comment by stemangiola** [comment]
@susansjy22 this line still includes a path that is not the local path. Please let me know if what is the problem is not clear.

https://github.com/susansjy22/HPCell/blob/1e3e452d4b23a45d3c8dc922211e9073b192ef64/README.rmd#L41C1-L42C1

**Comment by susansjy22** [comment]
> @susansjy22 this line still includes a path that is not the local path. Please let me know if what is the problem is not clear.
> 
> https://github.com/susansjy22/HPCell/blob/1e3e452d4b23a45d3c8dc922211e9073b192ef64/README.rmd#L41C1-L42C1
Fixed!
