### ISSUE TITLE
add documentation of the backend algorithms to README

### ISSUE THREAD

**Issue by stemangiola** [Melbourne-COVID-Predict/jascap#47]
Hello @susansjy22 ,
 
Could you please add the documentation for each pipeline step to the README at GitHub?
 
The document should include the methods used and snippets of the cord for how we use those methods with which parameters. The goal is for Aabeginner to understand what we are doing and why we are doing it.

**Comment by susansjy22** [comment]
Hi Stefano,

I've updated the README.rmd with documentation for each step within the run_targets_pipeline() function. The updated documentation is now available in the master branch of my GitHub repository.

Best,
Susan

**Comment by stemangiola** [comment]
Thanks,

maybe I am loggin the wrong place, I don't see the explanation of each step for a lay person in this page

https://github.com/susansjy22/HPCell

**Comment by susansjy22** [comment]
Hello Stefano,

I've made the updates, and you should now be able to see the changes at https://github.com/susansjy22/HPCell.
My apologies for the confusion earlier—I mixed up the two README files.

Susan

**Comment by stemangiola** [comment]
Thanks Susan,

I meant more as

"the pipeline has X stemps"

Step 1, does this and this, and this using this and this methods. Below is the code snippet of the methods used (e.g. 

```NormaliseCounts(parameters...))```

Step 2...
