### ISSUE TITLE
if filter = NULL test whether data has been filtered, and skip in case

### ISSUE THREAD

**Issue by stemangiola** [Melbourne-COVID-Predict/jascap#50]
@susansjy22 sometime, we don't know whether the date has been filtered so we can set up the default filter argument to NULL, and you can test within the filter function if the minimum RNA count per cell is X and assume that the data has been filtered already.

That X threshold can be found in the Surat tutorial

e.g.

` nFeature_RNA > 200 ` # This is RNa feature

from https://satijalab.org/seurat/archive/v3.0/pbmc3k_tutorial.html

and

` lower = 100,`. # This is RNa counts

from https://rdrr.io/github/MarioniLab/DropletUtils/man/emptyDrops.html

This will be done within the function of filtering, empty droplets, so some samples could have been filtered, and some samples could have not. The reports will show as they do know how many droplets wear filtered out in the user will be able to tell.

**Comment by myushen** [comment]
I wonder if pipeline running time is what enables this issue? What other impact might there be if users are unaware that  empty droplets have been filtered out from their data, and they continue using `filter_empty_droplets=TRUE`?

**Comment by stemangiola** [comment]
this is not an issue of running time. The consequence can be that you are filtering more cells than needed. If filter_empty_droplets = NULL by default, then an undecided user will use this. If they user changes the default, then they will put quite a lot of thoughts on it.

**Comment by myushen** [comment]
I don't think applying filter_empty_droplets=TRUE twice will filter out more cells since the threshold is set.  
I think a benefit of adding this function is giving users flexibility to choose the default cutoff applied by "filter_empty_droplets", or any other thresholds they prefer.

**Comment by stemangiola** [comment]
our empty droplet calculation is not base on a threshold, but on outliers.
