### ISSUE TITLE
Overwrite pipeline at every `execute_pipeline` call

### ISSUE THREAD

**Issue by stemangiola** [Melbourne-COVID-Predict/jascap#51]
@susansjy22 for the reasons we have discussed at the meeting let's overwrite the pipeline scraped every time we call the function so the bugging option can work properly.

We do not need to touch the store, just the R target script

**Comment by susansjy22** [comment]
Would using `tar_invalidate(names = target_to_overwrite, store = store)` address this? I think Targets caches the results of each pipeline run for efficiency when debugging a specific target, because not all of the previous targets to be re-run. Documentation for tar_invalidate: https://rdrr.io/cran/targets/man/tar_invalidate.html

**Comment by stemangiola** [comment]
Nom, to overwrite the pipeline (not the targets) ()the pipeline is a R file,  you do tar_script(ask=FALSE), which you already doing.

So if you remove the debug , the pipeline should not consider it anymore.

you can actually verify it, by opening manually your 

script = glue("{store}.R")

after doing debug (you should see the debug call)

and after not using debug

that debug call must disappear from the file, automatically

**Comment by myushen** [comment]
so the idea of this issue is to overwrite the script.R every time running the pipeline right? In your example @stemangiola , if removing a parameter e.g debug_step entirely in a second run , it should not exist in script.R

**Comment by stemangiola** [comment]
> so the idea of this issue is to overwrite the script.R every time running the pipeline right? In your example @stemangiola , if removing a parameter e.g debug_step entirely in a second run , it should not exist in script.R

correct.

The script glue("{store}.R")

should be updated to reflect that we switch on and off the debug

**but this should already be happening!** according to the code in github
